[2025-06-15T01:00:13.761+0100] {processor.py:161} INFO - Started process (PID=229779) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:00:13.762+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:00:13.763+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:00:13.762+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:00:13.764+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:00:13.764+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:00:13.764+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:00:13.764+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:00:13.764+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:00:13.770+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-15T01:00:58.001+0100] {processor.py:161} INFO - Started process (PID=230101) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:00:58.006+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:00:58.007+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:00:58.007+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:00:58.009+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:00:58.009+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:00:58.009+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:00:58.009+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:00:58.009+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:00:58.014+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-15T01:01:42.935+0100] {processor.py:161} INFO - Started process (PID=230526) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:01:42.940+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:01:42.941+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:01:42.941+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:01:42.942+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:01:42.942+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:01:42.943+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:01:42.942+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:01:42.943+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:01:42.948+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-15T01:02:27.975+0100] {processor.py:161} INFO - Started process (PID=230849) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:02:27.980+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:02:27.981+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:02:27.981+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:02:27.983+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:02:27.983+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:02:27.983+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:02:27.983+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:02:27.983+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:02:27.989+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T01:03:13.094+0100] {processor.py:161} INFO - Started process (PID=231129) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:03:13.095+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:03:13.096+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:03:13.095+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:03:13.097+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:03:13.097+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:03:13.097+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:03:13.097+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:03:13.097+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:03:13.102+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-15T01:03:58.963+0100] {processor.py:161} INFO - Started process (PID=231503) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:03:58.968+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:03:58.970+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:03:58.969+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:03:58.971+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:03:58.971+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:03:58.971+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:03:58.971+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:03:58.972+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:03:58.980+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-06-15T01:04:44.653+0100] {processor.py:161} INFO - Started process (PID=231868) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:04:44.654+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:04:44.655+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:04:44.655+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:04:44.656+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:04:44.656+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:04:44.657+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:04:44.656+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:04:44.657+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:04:44.662+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-15T01:05:31.259+0100] {processor.py:161} INFO - Started process (PID=232292) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:05:31.260+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:05:31.261+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:05:31.261+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:05:31.262+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:05:31.262+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:05:31.262+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:05:31.262+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:05:31.263+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:05:31.268+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-15T01:06:15.350+0100] {processor.py:161} INFO - Started process (PID=232590) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:06:15.355+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:06:15.356+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:06:15.356+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:06:15.359+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:06:15.358+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:06:15.359+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:06:15.359+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:06:15.359+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:06:15.364+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T01:07:00.779+0100] {processor.py:161} INFO - Started process (PID=232931) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:07:00.784+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:07:00.785+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:07:00.785+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:07:00.787+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:07:00.787+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:07:00.787+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:07:00.787+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:07:00.787+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:07:00.793+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-06-15T01:08:03.184+0100] {processor.py:161} INFO - Started process (PID=233474) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:08:03.185+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:08:03.187+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:08:03.186+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:08:03.189+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:08:03.189+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:08:03.189+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:08:03.189+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:08:03.190+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:08:03.196+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-15T01:08:49.186+0100] {processor.py:161} INFO - Started process (PID=233828) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:08:49.191+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:08:49.192+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:08:49.192+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:08:49.193+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:08:49.193+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:08:49.194+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:08:49.194+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:08:49.194+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:08:49.199+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-15T01:09:35.169+0100] {processor.py:161} INFO - Started process (PID=234197) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:09:35.174+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:09:35.175+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:09:35.175+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:09:35.177+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:09:35.177+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:09:35.177+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:09:35.177+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:09:35.177+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:09:35.183+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T01:10:20.448+0100] {processor.py:161} INFO - Started process (PID=234611) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:10:20.449+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:10:20.450+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:10:20.449+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:10:20.451+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:10:20.451+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:10:20.451+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:10:20.451+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:10:20.451+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:10:20.457+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T01:11:38.856+0100] {processor.py:161} INFO - Started process (PID=235912) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:11:38.861+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:11:38.863+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:11:38.862+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:11:38.865+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:11:38.865+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:11:38.865+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:11:38.865+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:11:38.866+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:11:38.871+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-06-15T01:12:30.056+0100] {processor.py:161} INFO - Started process (PID=236375) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:12:30.062+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:12:30.063+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:12:30.063+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:12:30.065+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:12:30.064+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:12:30.065+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:12:30.065+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:12:30.065+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:12:30.070+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T01:13:16.496+0100] {processor.py:161} INFO - Started process (PID=236795) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:13:16.502+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:13:16.503+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:13:16.502+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:13:16.504+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:13:16.504+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:13:16.504+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:13:16.504+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:13:16.504+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:13:16.510+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T01:14:06.253+0100] {processor.py:161} INFO - Started process (PID=237319) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:14:06.259+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:14:06.260+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:14:06.259+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:14:06.261+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:14:06.261+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:14:06.261+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:14:06.261+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:14:06.261+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:14:06.266+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-15T01:14:52.310+0100] {processor.py:161} INFO - Started process (PID=238006) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:14:52.315+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:14:52.316+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:14:52.315+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:14:52.317+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:14:52.317+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:14:52.317+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:14:52.317+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:14:52.317+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:14:52.323+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T01:15:53.494+0100] {processor.py:161} INFO - Started process (PID=238894) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:15:53.499+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:15:53.500+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:15:53.500+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:15:53.501+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:15:53.501+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:15:53.502+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:15:53.502+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:15:53.502+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:15:53.507+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T01:17:04.146+0100] {processor.py:161} INFO - Started process (PID=240217) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:17:04.152+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:17:04.153+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:17:04.153+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:17:04.155+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:17:04.155+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:17:04.155+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:17:04.155+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:17:04.155+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:17:04.161+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-06-15T01:18:00.253+0100] {processor.py:161} INFO - Started process (PID=240698) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:18:00.259+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:18:00.260+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:18:00.260+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:18:00.261+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:18:00.261+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:18:00.261+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:18:00.261+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:18:00.262+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:18:00.267+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T01:18:54.259+0100] {processor.py:161} INFO - Started process (PID=241077) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:18:54.264+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:18:54.265+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:18:54.265+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:18:54.266+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:18:54.266+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:18:54.266+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:18:54.266+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:18:54.266+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:18:54.272+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-15T01:19:39.405+0100] {processor.py:161} INFO - Started process (PID=241386) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:19:39.406+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:19:39.407+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:19:39.407+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:19:39.408+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:19:39.408+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:19:39.408+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:19:39.408+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:19:39.408+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:19:39.414+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-15T01:20:28.622+0100] {processor.py:161} INFO - Started process (PID=241714) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:20:28.627+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:20:28.628+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:20:28.628+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:20:28.630+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:20:28.630+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:20:28.630+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:20:28.630+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:20:28.630+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:20:28.636+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T01:21:11.576+0100] {processor.py:161} INFO - Started process (PID=241973) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:21:11.581+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:21:11.582+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:21:11.582+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:21:11.584+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:21:11.583+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:21:11.584+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:21:11.584+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:21:11.584+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:21:11.589+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T01:21:57.600+0100] {processor.py:161} INFO - Started process (PID=242328) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:21:57.605+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:21:57.607+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:21:57.606+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:21:57.608+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:21:57.608+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:21:57.608+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:21:57.608+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:21:57.609+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:21:57.614+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-06-15T01:22:41.200+0100] {processor.py:161} INFO - Started process (PID=253186) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:22:41.200+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T01:22:41.201+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:22:41.201+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:22:41.203+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:22:41.203+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T01:22:41.203+0100] {logging_mixin.py:188} INFO - [2025-06-15T01:22:41.203+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T01:22:41.203+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T01:22:41.210+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T07:56:56.293+0100] {processor.py:161} INFO - Started process (PID=254011) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T07:56:56.294+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T07:56:56.295+0100] {logging_mixin.py:188} INFO - [2025-06-15T07:56:56.295+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T07:56:56.297+0100] {logging_mixin.py:188} INFO - [2025-06-15T07:56:56.296+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T07:56:56.297+0100] {logging_mixin.py:188} INFO - [2025-06-15T07:56:56.297+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T07:56:56.297+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T07:56:56.304+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-15T07:57:44.008+0100] {processor.py:161} INFO - Started process (PID=254436) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T07:57:44.009+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T07:57:44.010+0100] {logging_mixin.py:188} INFO - [2025-06-15T07:57:44.010+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T07:57:44.012+0100] {logging_mixin.py:188} INFO - [2025-06-15T07:57:44.011+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T07:57:44.012+0100] {logging_mixin.py:188} INFO - [2025-06-15T07:57:44.012+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T07:57:44.012+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T07:57:44.021+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-15T07:58:44.855+0100] {processor.py:161} INFO - Started process (PID=254655) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T07:58:44.860+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T07:58:44.861+0100] {logging_mixin.py:188} INFO - [2025-06-15T07:58:44.861+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T07:58:44.862+0100] {logging_mixin.py:188} INFO - [2025-06-15T07:58:44.862+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T07:58:44.862+0100] {logging_mixin.py:188} INFO - [2025-06-15T07:58:44.862+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T07:58:44.863+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T07:58:44.868+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-15T07:59:44.653+0100] {processor.py:161} INFO - Started process (PID=254998) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T07:59:44.658+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T07:59:44.659+0100] {logging_mixin.py:188} INFO - [2025-06-15T07:59:44.659+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T07:59:44.661+0100] {logging_mixin.py:188} INFO - [2025-06-15T07:59:44.661+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T07:59:44.662+0100] {logging_mixin.py:188} INFO - [2025-06-15T07:59:44.662+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T07:59:44.662+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T07:59:44.667+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T08:00:40.085+0100] {processor.py:161} INFO - Started process (PID=255954) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:00:40.090+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T08:00:40.091+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:00:40.091+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:00:40.093+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:00:40.093+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T08:00:40.093+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:00:40.093+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T08:00:40.093+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:00:40.099+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T08:01:39.203+0100] {processor.py:161} INFO - Started process (PID=256287) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:01:39.203+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T08:01:39.204+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:01:39.204+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:01:39.206+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:01:39.206+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T08:01:39.206+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:01:39.206+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T08:01:39.206+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:01:39.212+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T08:02:37.366+0100] {processor.py:161} INFO - Started process (PID=256647) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:02:37.371+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T08:02:37.373+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:02:37.372+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:02:37.374+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:02:37.374+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T08:02:37.375+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:02:37.374+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T08:02:37.375+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:02:37.381+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-06-15T08:03:21.597+0100] {processor.py:161} INFO - Started process (PID=256858) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:03:21.601+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T08:03:21.602+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:03:21.602+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:03:21.603+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:03:21.603+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T08:03:21.604+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:03:21.603+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T08:03:21.604+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:03:21.609+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-15T08:04:19.989+0100] {processor.py:161} INFO - Started process (PID=257192) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:04:19.995+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T08:04:19.996+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:04:19.996+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:04:19.998+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:04:19.997+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T08:04:19.998+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:04:19.998+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T08:04:19.998+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:04:20.004+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T08:05:15.254+0100] {processor.py:161} INFO - Started process (PID=257604) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:05:15.260+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T08:05:15.261+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:05:15.261+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:05:15.263+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:05:15.263+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T08:05:15.264+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:05:15.264+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T08:05:15.264+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:05:15.270+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-06-15T08:06:12.390+0100] {processor.py:161} INFO - Started process (PID=257963) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:06:12.396+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T08:06:12.397+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:06:12.397+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:06:12.398+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:06:12.398+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T08:06:12.399+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:06:12.399+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T08:06:12.399+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:06:12.405+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-06-15T08:07:07.792+0100] {processor.py:161} INFO - Started process (PID=258312) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:07:07.797+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T08:07:07.798+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:07:07.798+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:07:07.800+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:07:07.799+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T08:07:07.800+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:07:07.800+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T08:07:07.800+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:07:07.806+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-06-15T08:08:06.323+0100] {processor.py:161} INFO - Started process (PID=258670) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:08:06.324+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T08:08:06.325+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:08:06.325+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:08:06.326+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:08:06.326+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T08:08:06.326+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:08:06.326+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T08:08:06.327+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:08:06.332+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T08:09:02.958+0100] {processor.py:161} INFO - Started process (PID=259026) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:09:02.959+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T08:09:02.960+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:09:02.960+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:09:02.962+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:09:02.961+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T08:09:02.962+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:09:02.962+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T08:09:02.962+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:09:02.967+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T08:09:54.591+0100] {processor.py:161} INFO - Started process (PID=259399) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:09:54.596+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T08:09:54.597+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:09:54.597+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:09:54.599+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:09:54.599+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T08:09:54.599+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:09:54.599+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T08:09:54.599+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:09:54.605+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T08:10:50.963+0100] {processor.py:161} INFO - Started process (PID=259789) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:10:50.964+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T08:10:50.965+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:10:50.965+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:10:50.967+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:10:50.966+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T08:10:50.967+0100] {logging_mixin.py:188} INFO - [2025-06-15T08:10:50.967+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T08:10:50.967+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T08:10:50.972+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T10:14:58.516+0100] {processor.py:161} INFO - Started process (PID=298985) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:14:58.522+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T10:14:58.523+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:14:58.523+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:14:58.524+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:14:58.524+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T10:14:58.525+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:14:58.525+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T10:14:58.525+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:14:58.530+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T10:15:49.872+0100] {processor.py:161} INFO - Started process (PID=299353) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:15:49.878+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T10:15:49.878+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:15:49.878+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:15:49.880+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:15:49.880+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T10:15:49.880+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:15:49.880+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T10:15:49.880+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:15:49.886+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T10:16:35.527+0100] {processor.py:161} INFO - Started process (PID=299610) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:16:35.532+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T10:16:35.533+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:16:35.533+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:16:35.535+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:16:35.535+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T10:16:35.535+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:16:35.535+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T10:16:35.535+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:16:35.540+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T10:17:31.098+0100] {processor.py:161} INFO - Started process (PID=299876) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:17:31.103+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T10:17:31.104+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:17:31.104+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:17:31.105+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:17:31.105+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T10:17:31.106+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:17:31.106+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T10:17:31.106+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:17:31.111+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T10:18:28.588+0100] {processor.py:161} INFO - Started process (PID=300293) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:18:28.589+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T10:18:28.590+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:18:28.590+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:18:28.592+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:18:28.591+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T10:18:28.592+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:18:28.592+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T10:18:28.592+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:18:28.598+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T10:19:22.600+0100] {processor.py:161} INFO - Started process (PID=300722) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:19:22.601+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T10:19:22.602+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:19:22.601+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:19:22.603+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:19:22.603+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T10:19:22.603+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:19:22.603+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T10:19:22.603+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:19:22.609+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-15T10:20:19.101+0100] {processor.py:161} INFO - Started process (PID=301022) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:20:19.103+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T10:20:19.104+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:20:19.103+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:20:19.106+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:20:19.106+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T10:20:19.106+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:20:19.106+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T10:20:19.106+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:20:19.113+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-15T10:21:58.298+0100] {processor.py:161} INFO - Started process (PID=301642) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:21:58.299+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T10:21:58.300+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:21:58.300+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:21:58.301+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:21:58.301+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T10:21:58.301+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:21:58.301+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T10:21:58.302+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:21:58.307+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T10:22:46.564+0100] {processor.py:161} INFO - Started process (PID=301817) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:22:46.569+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T10:22:46.570+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:22:46.570+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:22:46.572+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:22:46.572+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T10:22:46.572+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:22:46.572+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T10:22:46.572+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:22:46.577+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T10:23:35.797+0100] {processor.py:161} INFO - Started process (PID=301941) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:23:35.803+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T10:23:35.804+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:23:35.804+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:23:35.806+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:23:35.805+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T10:23:35.806+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:23:35.806+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T10:23:35.806+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:23:35.811+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T10:24:31.498+0100] {processor.py:161} INFO - Started process (PID=302299) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:24:31.499+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T10:24:31.501+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:24:31.500+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:24:31.502+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:24:31.502+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T10:24:31.502+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:24:31.502+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T10:24:31.502+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:24:31.509+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-15T10:25:29.152+0100] {processor.py:161} INFO - Started process (PID=302681) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:25:29.157+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T10:25:29.158+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:25:29.158+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:25:29.159+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:25:29.159+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T10:25:29.160+0100] {logging_mixin.py:188} INFO - [2025-06-15T10:25:29.160+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T10:25:29.160+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T10:25:29.165+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-06-15T11:45:54.500+0100] {processor.py:161} INFO - Started process (PID=323804) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T11:45:54.505+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T11:45:54.506+0100] {logging_mixin.py:188} INFO - [2025-06-15T11:45:54.506+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T11:45:54.508+0100] {logging_mixin.py:188} INFO - [2025-06-15T11:45:54.507+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T11:45:54.508+0100] {logging_mixin.py:188} INFO - [2025-06-15T11:45:54.508+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T11:45:54.508+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T11:45:54.515+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-06-15T11:46:43.804+0100] {processor.py:161} INFO - Started process (PID=324220) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T11:46:43.805+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T11:46:43.806+0100] {logging_mixin.py:188} INFO - [2025-06-15T11:46:43.806+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T11:46:43.808+0100] {logging_mixin.py:188} INFO - [2025-06-15T11:46:43.808+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T11:46:43.808+0100] {logging_mixin.py:188} INFO - [2025-06-15T11:46:43.808+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T11:46:43.808+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T11:46:43.813+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-15T11:47:33.362+0100] {processor.py:161} INFO - Started process (PID=324538) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T11:47:33.368+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T11:47:33.369+0100] {logging_mixin.py:188} INFO - [2025-06-15T11:47:33.369+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T11:47:33.371+0100] {logging_mixin.py:188} INFO - [2025-06-15T11:47:33.370+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T11:47:33.371+0100] {logging_mixin.py:188} INFO - [2025-06-15T11:47:33.371+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T11:47:33.371+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T11:47:33.380+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-06-15T11:48:31.059+0100] {processor.py:161} INFO - Started process (PID=324957) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T11:48:31.064+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T11:48:31.066+0100] {logging_mixin.py:188} INFO - [2025-06-15T11:48:31.065+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T11:48:31.071+0100] {logging_mixin.py:188} INFO - [2025-06-15T11:48:31.070+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T11:48:31.072+0100] {logging_mixin.py:188} INFO - [2025-06-15T11:48:31.071+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T11:48:31.072+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T11:48:31.083+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-06-15T11:49:26.133+0100] {processor.py:161} INFO - Started process (PID=325319) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T11:49:26.139+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T11:49:26.140+0100] {logging_mixin.py:188} INFO - [2025-06-15T11:49:26.140+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T11:49:26.141+0100] {logging_mixin.py:188} INFO - [2025-06-15T11:49:26.141+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T11:49:26.142+0100] {logging_mixin.py:188} INFO - [2025-06-15T11:49:26.142+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T11:49:26.142+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T11:49:26.147+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T18:13:30.400+0100] {processor.py:161} INFO - Started process (PID=475364) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:13:30.401+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:13:30.402+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:13:30.402+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:13:30.403+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:13:30.403+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:13:30.404+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:13:30.404+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:13:30.404+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:13:30.409+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-15T18:14:22.418+0100] {processor.py:161} INFO - Started process (PID=475677) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:14:22.419+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:14:22.420+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:14:22.420+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:14:22.422+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:14:22.422+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:14:22.422+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:14:22.422+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:14:22.423+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:14:22.430+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-15T18:24:44.163+0100] {processor.py:161} INFO - Started process (PID=481202) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:24:44.169+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:24:44.170+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:24:44.169+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:24:44.171+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:24:44.171+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:24:44.172+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:24:44.171+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:24:44.172+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:24:44.178+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-06-15T18:25:34.545+0100] {processor.py:161} INFO - Started process (PID=481511) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:25:34.550+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:25:34.551+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:25:34.551+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:25:34.553+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:25:34.553+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:25:34.553+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:25:34.553+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:25:34.553+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:25:34.559+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T18:26:23.722+0100] {processor.py:161} INFO - Started process (PID=481936) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:26:23.723+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:26:23.724+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:26:23.723+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:26:23.725+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:26:23.725+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:26:23.726+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:26:23.726+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:26:23.726+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:26:23.731+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-15T18:27:36.746+0100] {processor.py:161} INFO - Started process (PID=482773) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:27:36.746+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:27:36.747+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:27:36.747+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:27:36.749+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:27:36.749+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:27:36.749+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:27:36.749+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:27:36.749+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:27:36.755+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-15T18:28:24.613+0100] {processor.py:161} INFO - Started process (PID=483227) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:28:24.613+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:28:24.614+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:28:24.614+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:28:24.616+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:28:24.616+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:28:24.616+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:28:24.616+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:28:24.616+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:28:24.622+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-15T18:29:14.613+0100] {processor.py:161} INFO - Started process (PID=483611) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:29:14.619+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:29:14.620+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:29:14.620+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:29:14.622+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:29:14.621+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:29:14.622+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:29:14.622+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:29:14.622+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:29:14.628+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-06-15T18:31:24.481+0100] {processor.py:161} INFO - Started process (PID=486007) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:31:24.482+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:31:24.483+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:31:24.483+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:31:24.485+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:31:24.484+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:31:24.485+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:31:24.485+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:31:24.485+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:31:24.491+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T18:32:13.536+0100] {processor.py:161} INFO - Started process (PID=486569) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:32:13.537+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:32:13.538+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:32:13.537+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:32:13.539+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:32:13.539+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:32:13.539+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:32:13.539+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:32:13.539+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:32:13.545+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T18:33:03.303+0100] {processor.py:161} INFO - Started process (PID=487506) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:33:03.304+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:33:03.304+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:33:03.304+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:33:03.306+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:33:03.306+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:33:03.306+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:33:03.306+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:33:03.306+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:33:03.312+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-15T18:34:08.660+0100] {processor.py:161} INFO - Started process (PID=488794) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:34:08.666+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:34:08.667+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:34:08.666+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:34:08.668+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:34:08.668+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:34:08.668+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:34:08.668+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:34:08.668+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:34:08.673+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T18:35:07.503+0100] {processor.py:161} INFO - Started process (PID=489280) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:35:07.508+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:35:07.509+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:35:07.509+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:35:07.511+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:35:07.510+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:35:07.511+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:35:07.511+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:35:07.511+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:35:07.517+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T18:36:06.987+0100] {processor.py:161} INFO - Started process (PID=489729) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:36:06.993+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:36:06.993+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:36:06.993+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:36:06.995+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:36:06.995+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:36:06.995+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:36:06.995+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:36:06.995+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:36:07.000+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T18:36:49.906+0100] {processor.py:161} INFO - Started process (PID=490248) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:36:49.911+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:36:49.912+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:36:49.912+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:36:49.914+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:36:49.913+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:36:49.914+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:36:49.914+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:36:49.914+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:36:49.919+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T18:37:31.658+0100] {processor.py:161} INFO - Started process (PID=490613) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:37:31.663+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:37:31.664+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:37:31.664+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:37:31.666+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:37:31.665+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:37:31.666+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:37:31.666+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:37:31.666+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:37:31.672+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T18:38:32.414+0100] {processor.py:161} INFO - Started process (PID=491174) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:38:32.415+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:38:32.416+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:38:32.416+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:38:32.417+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:38:32.417+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:38:32.418+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:38:32.418+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:38:32.418+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:38:32.424+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-15T18:39:13.108+0100] {processor.py:161} INFO - Started process (PID=491540) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:39:13.113+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:39:13.114+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:39:13.114+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:39:13.116+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:39:13.115+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:39:13.116+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:39:13.116+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:39:13.116+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:39:13.121+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-06-15T18:40:13.509+0100] {processor.py:161} INFO - Started process (PID=492121) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:40:13.514+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:40:13.515+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:40:13.515+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:40:13.517+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:40:13.517+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:40:13.517+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:40:13.517+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:40:13.517+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:40:13.523+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T18:40:57.693+0100] {processor.py:161} INFO - Started process (PID=492483) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:40:57.694+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:40:57.695+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:40:57.695+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:40:57.696+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:40:57.696+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:40:57.697+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:40:57.697+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:40:57.697+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:40:57.702+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-15T18:41:54.755+0100] {processor.py:161} INFO - Started process (PID=493050) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:41:54.756+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:41:54.757+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:41:54.757+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:41:54.759+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:41:54.759+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:41:54.759+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:41:54.759+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:41:54.759+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:41:54.765+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T18:42:38.019+0100] {processor.py:161} INFO - Started process (PID=493377) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:42:38.020+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:42:38.021+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:42:38.020+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:42:38.022+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:42:38.022+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:42:38.023+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:42:38.022+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:42:38.023+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:42:38.029+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T18:43:19.532+0100] {processor.py:161} INFO - Started process (PID=493650) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:43:19.533+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:43:19.534+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:43:19.534+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:43:19.536+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:43:19.535+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:43:19.536+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:43:19.536+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:43:19.536+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:43:19.542+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T18:44:17.406+0100] {processor.py:161} INFO - Started process (PID=494033) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:44:17.407+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:44:17.408+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:44:17.407+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:44:17.409+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:44:17.409+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:44:17.410+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:44:17.409+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:44:17.410+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:44:17.416+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T18:44:59.045+0100] {processor.py:161} INFO - Started process (PID=494209) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:44:59.045+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:44:59.047+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:44:59.047+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:44:59.049+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:44:59.049+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:44:59.049+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:44:59.049+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:44:59.049+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:44:59.057+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-15T18:45:37.354+0100] {processor.py:161} INFO - Started process (PID=494449) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:45:37.355+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:45:37.356+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:45:37.356+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:45:37.358+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:45:37.358+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:45:37.358+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:45:37.358+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:45:37.358+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:45:37.365+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-15T18:46:20.927+0100] {processor.py:161} INFO - Started process (PID=494779) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:46:20.928+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:46:20.929+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:46:20.929+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:46:20.931+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:46:20.930+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:46:20.931+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:46:20.931+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:46:20.931+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:46:20.937+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T18:47:03.773+0100] {processor.py:161} INFO - Started process (PID=494957) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:47:03.774+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:47:03.775+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:47:03.774+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:47:03.776+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:47:03.776+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:47:03.776+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:47:03.776+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:47:03.776+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:47:03.782+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T18:48:00.618+0100] {processor.py:161} INFO - Started process (PID=495335) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:48:00.623+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:48:00.624+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:48:00.624+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:48:00.626+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:48:00.626+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:48:00.626+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:48:00.626+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:48:00.627+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:48:00.633+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-06-15T18:53:32.849+0100] {processor.py:161} INFO - Started process (PID=497083) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:53:32.854+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:53:32.855+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:53:32.855+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:53:32.856+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:53:32.856+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:53:32.856+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:53:32.856+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:53:32.857+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:53:32.864+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-06-15T18:54:23.254+0100] {processor.py:161} INFO - Started process (PID=497803) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:54:23.255+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:54:23.256+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:54:23.256+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:54:23.258+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:54:23.258+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:54:23.258+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:54:23.258+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:54:23.258+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:54:23.263+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T18:55:12.519+0100] {processor.py:161} INFO - Started process (PID=498524) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:55:12.520+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:55:12.521+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:55:12.520+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:55:12.522+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:55:12.522+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:55:12.523+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:55:12.523+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:55:12.523+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:55:12.528+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T18:55:53.693+0100] {processor.py:161} INFO - Started process (PID=499131) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:55:53.693+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:55:53.694+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:55:53.694+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:55:53.696+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:55:53.696+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:55:53.696+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:55:53.696+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:55:53.696+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:55:53.701+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-15T18:56:37.603+0100] {processor.py:161} INFO - Started process (PID=499725) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:56:37.604+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:56:37.605+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:56:37.605+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:56:37.607+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:56:37.606+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:56:37.607+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:56:37.607+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:56:37.607+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:56:37.614+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-15T18:57:18.204+0100] {processor.py:161} INFO - Started process (PID=500268) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:57:18.205+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T18:57:18.206+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:57:18.206+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:57:18.208+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:57:18.208+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T18:57:18.208+0100] {logging_mixin.py:188} INFO - [2025-06-15T18:57:18.208+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T18:57:18.209+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T18:57:18.216+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-15T20:06:59.466+0100] {processor.py:161} INFO - Started process (PID=532209) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T20:06:59.471+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T20:06:59.472+0100] {logging_mixin.py:188} INFO - [2025-06-15T20:06:59.472+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T20:06:59.474+0100] {logging_mixin.py:188} INFO - [2025-06-15T20:06:59.474+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T20:06:59.475+0100] {logging_mixin.py:188} INFO - [2025-06-15T20:06:59.474+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T20:06:59.475+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T20:06:59.483+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-06-15T20:15:04.160+0100] {processor.py:161} INFO - Started process (PID=538563) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T20:15:04.165+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T20:15:04.166+0100] {logging_mixin.py:188} INFO - [2025-06-15T20:15:04.166+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T20:15:04.168+0100] {logging_mixin.py:188} INFO - [2025-06-15T20:15:04.167+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T20:15:04.168+0100] {logging_mixin.py:188} INFO - [2025-06-15T20:15:04.168+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T20:15:04.168+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T20:15:04.173+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T20:25:12.185+0100] {processor.py:161} INFO - Started process (PID=546665) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T20:25:12.185+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T20:25:12.186+0100] {logging_mixin.py:188} INFO - [2025-06-15T20:25:12.186+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T20:25:12.188+0100] {logging_mixin.py:188} INFO - [2025-06-15T20:25:12.188+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T20:25:12.188+0100] {logging_mixin.py:188} INFO - [2025-06-15T20:25:12.188+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T20:25:12.188+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T20:25:12.194+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-15T20:32:37.893+0100] {processor.py:161} INFO - Started process (PID=552823) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T20:32:37.899+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T20:32:37.900+0100] {logging_mixin.py:188} INFO - [2025-06-15T20:32:37.900+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T20:32:37.901+0100] {logging_mixin.py:188} INFO - [2025-06-15T20:32:37.901+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T20:32:37.901+0100] {logging_mixin.py:188} INFO - [2025-06-15T20:32:37.901+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T20:32:37.902+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T20:32:37.907+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-15T21:00:52.539+0100] {processor.py:161} INFO - Started process (PID=565377) to work on /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T21:00:52.540+0100] {processor.py:830} INFO - Processing file /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-15T21:00:52.541+0100] {logging_mixin.py:188} INFO - [2025-06-15T21:00:52.541+0100] {dagbag.py:545} INFO - Filling up the DagBag from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T21:00:52.542+0100] {logging_mixin.py:188} INFO - [2025-06-15T21:00:52.542+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-15T21:00:52.543+0100] {logging_mixin.py:188} INFO - [2025-06-15T21:00:52.543+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-15T21:00:52.543+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-15T21:00:52.548+0100] {processor.py:183} INFO - Processing /home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
